Foun_Eng = float(89.5)
Gen_Bus = float(74)
ICS = float(93.5)
Com_Pro = float(86)
print("--- Your Score ---")
print("Foundation English               :", Foun_Eng)
print("General Business                 :", Gen_Bus)
print("Introduction to Computer Systems :", ICS)
print("Computer Programming             :", Com_Pro)